export const items = [
  "Sorry, I didn't realise I was on mute.",
  "Can we take this offline?",
  "Just wanted to loop you in.",
  "Can everyone mute themselves?",
  "Waiting for host to start the meeting.",
  "*Children noises in the background*",
  "Have to hop on another call.",
  "Do you see my screen?",
  "Can we push this meeting back ___ minutes.",
  "I'll have to get back to you.",
  "You're still sharing your screen.",
  "*Loud keyboard typing*",
  "Hold on. Let me switch out my headphones.",
  "I want to stop hear for any questions.",
  "Don't all speak at once!",
  "*Interruption* Sorry, you go ahead*",
  "*Animal noises in the background*",
  "Let's wait for ___ to join the call.",
  "Couldn't find the conference ID for the meeting",
  "We have enough people now. Let's start on the agenda.",
  "*Everyone saying goodbye at the end of the meeting*",
  "*Echo, feeback or bad connection*",
  "There's only ___ minutes left in the meeting",
  "Can you guys hear me?",
  "Oops, it looks like we've lost ___",
];
export const winningCombination = [
  [0, 1, 2, 3, 4],
  [5, 6, 7, 8, 9],
  [10, 11, 13, 14],
  [15, 16, 17, 18, 19],
  [20, 21, 22, 23, 24],
  [0, 5, 10, 15, 20],
  [1, 6, 11, 16, 21],
  [2, 7, 17, 22],
  [3, 8, 13, 18, 23],
  [4, 9, 14, 19, 24],
  [0, 6, 18, 24],
  [4, 8, 16, 20],
];
